/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Datos.ConexionBD;
import Datos.DAltas;
import Datos.DPagos;
import Metodos.Metodos_Consulta_Rapida;
import Puentes.PuenteAltas;
import Puentes.PuenteConsultaRapida;
import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AlejandroSaenz
 */
public class ConsultaRapida extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaRapida
     */
    public ConsultaRapida() {
         
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setLocationRelativeTo(null);
    this.Hoy.setDate(Fecha());
    this.Hoy.setEnabled(false);
    this.ProximoPago.setEnabled(false);
    this.txtTipo.setEnabled(false);
    }

  public static Date Fecha() {
    Date FechaA = new Date();
    SimpleDateFormat FormatoFecha = new SimpleDateFormat("dd/MM/YYYY");
    return FechaA;
  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaDatos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        txtApe = new javax.swing.JTextField();
        txtNom = new javax.swing.JTextField();
        txtTipo = new javax.swing.JTextField();
        estado = new javax.swing.JTextField();
        LbNombre = new javax.swing.JLabel();
        LbApellido = new javax.swing.JLabel();
        ProximoPago = new com.toedter.calendar.JDateChooser();
        Hoy = new com.toedter.calendar.JDateChooser();
        lbMostrarImagen = new javax.swing.JLabel();
        nam = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel2.setText("Busqueda");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Id:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 45, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 97, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Apellidos:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 97, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nombre:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 151, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Apellidos:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 209, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Proximo pago:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 256, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Estado:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 314, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Tipo de pago:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 352, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Historial de Pagos");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 382, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel12.setText("Hoy");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 650, -1, -1));

        TablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TablaDatos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 650, 185));

        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 640, -1, -1));

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdKeyTyped(evt);
            }
        });
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 44, 325, -1));

        txtApe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApeActionPerformed(evt);
            }
        });
        txtApe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtApeKeyPressed(evt);
            }
        });
        getContentPane().add(txtApe, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 96, 186, -1));

        txtNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomActionPerformed(evt);
            }
        });
        getContentPane().add(txtNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 96, 186, -1));
        getContentPane().add(txtTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 351, 306, -1));
        getContentPane().add(estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 313, 306, -1));

        LbNombre.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        LbNombre.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(LbNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 151, -1, -1));

        LbApellido.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        LbApellido.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(LbApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 209, -1, -1));
        getContentPane().add(ProximoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 260, 306, -1));
        getContentPane().add(Hoy, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 650, 231, -1));

        lbMostrarImagen.setBorder(javax.swing.BorderFactory.createTitledBorder("Fotografia"));
        getContentPane().add(lbMostrarImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, 220, 180));

        nam.setText("Usuario");
        getContentPane().add(nam, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 270, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Gym3.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
Sistema si=new Sistema();
si.setVisible(true);
si.user.setText(nam.getText());
dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
void Limpiar() {
    this.LbNombre.setText("");
    this.LbApellido.setText("");
    this.estado.setText("");
    this.estado.setBackground((Color)null);
  }
void MostrarTabla() {
    (new PuenteConsultaRapida()).PuenteMostrarTabla(this.TablaDatos, this.txtId);
  }
 public void CalcularDias(JDateChooser Hoy, JDateChooser ProximoPago){
     if (Hoy.getDate() != null && ProximoPago.getDate() != null) {
      Calendar inicio = Hoy.getCalendar();
      Calendar Termino = ProximoPago.getCalendar();
      int dias = 0;
     
        while (inicio.before(Termino) || inicio.equals(Termino)) {
          dias++;
         inicio.add(Calendar.DATE,1);          
        }  
        if(dias>=20){estado.setText("Activo, su membresia vence en: +"+dias+"dias"); estado.setBackground(Color.green);TablaDatos.setBackground(Color.green); }
          if(dias>=7&&dias<=19){estado.setText("Activo su membresia vence en: +"+dias+"dias");estado.setBackground(Color.green); TablaDatos.setBackground(Color.green);}
          if(dias>=1&&dias<=6){estado.setText("Atencion, su membresia vence en: +"+dias+"dias");estado.setBackground(Color.YELLOW); TablaDatos.setBackground(Color.YELLOW);}
          if(dias<=0){estado.setText("Vencido: porfavor pague su membresia");
          estado.setBackground(Color.red);
          TablaDatos.setBackground(Color.red);
        System.out.println(dias);}}
 }
    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
try{
        if (!this.txtId.getText().isEmpty()) {
      this.lbMostrarImagen.setIcon((Icon)null);
      this.txtNom.setText("");
      this.txtApe.setText("");
      Limpiar();
      MostrarTabla();
      DPagos Prov = new DPagos();
      Prov.setId(Integer.parseInt(this.txtId.getText()));
      (new Metodos_Consulta_Rapida()).consultaFolio(Prov);
      this.ProximoPago.setDate(Prov.getProximo_Pago());
      this.txtTipo.setText(Prov.getTipo());
      DAltas prov = new DAltas();
      prov.setId(Integer.parseInt(this.txtId.getText()));
      (new PuenteAltas()).PuenteBuscar(prov);
      this.LbNombre.setText("" + prov.getNombre());
      this.LbApellido.setText("" + prov.getApellidos());
      this.TablaDatos.setVisible(true);
      int clv = Integer.parseInt(this.txtId.getText());
      ImageIcon img = (new PuenteAltas()).puenteObtenerImagen(clv);
      Icon icono = new ImageIcon(img.getImage().getScaledInstance(this.lbMostrarImagen.getWidth(), this.lbMostrarImagen.getHeight(), 1));
      if (img != null) {
        this.lbMostrarImagen.setIcon(icono);
        CalcularDias(this.Hoy, this.ProximoPago);
      } 
    } else {
      JOptionPane.showMessageDialog(null, "Debes introducir un Numero de control", "Aviso", 1);
    }}catch(Exception e){System.out.println(e);}        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed
  
  void MostrarTabla2() {
    (new PuenteConsultaRapida()).PuenteMostrarTabla2(this.TablaDatos, this.txtNom, this.txtApe);
  }
  
  void MostrarTabla3() {
    (new PuenteConsultaRapida()).PuenteMostrarTabla3(this.TablaDatos, this.txtNom);
  }
  
  void MostrarTabla4() {
    (new PuenteConsultaRapida()).PuenteMostrarTabla4(this.TablaDatos, this.txtApe);
  }
    private void txtNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomActionPerformed

        try{
            if (this.txtNom.getText().isEmpty() && this.txtApe.getText().isEmpty()) {
      JOptionPane.showMessageDialog(null, "Debes introducir Nombre y Apellido", "Aviso", 1);
    } else if (this.txtApe.getText().isEmpty() && !this.txtNom.getText().isEmpty()) {
      this.txtId.setText("");
      Limpiar();
      this.lbMostrarImagen.setIcon((Icon)null);
      MostrarTabla3();
      DPagos Prov = new DPagos();
      Prov.setNombre(this.txtNom.getText());
      (new Metodos_Consulta_Rapida()).consultaFolio3(Prov);
      this.ProximoPago.setDate(Prov.getProximo_Pago());
      this.txtTipo.setText(Prov.getTipo());
      DAltas prov = new DAltas();
      prov.setNombre(this.txtNom.getText());
      (new PuenteAltas()).PuenteBuscar3(prov);
      this.LbNombre.setText("" + prov.getNombre());
      String Nombre = this.txtNom.getText();
      ImageIcon img = (new PuenteAltas()).puenteObtenerImagen3(Nombre);
      Icon icono = new ImageIcon(img.getImage().getScaledInstance(this.lbMostrarImagen.getWidth(), this.lbMostrarImagen.getHeight(), 1));
      if (img != null) {
        this.lbMostrarImagen.setIcon(icono);
        CalcularDias(this.Hoy, this.ProximoPago);
      } 
      this.TablaDatos.setVisible(true);
    } else if (!this.txtApe.getText().isEmpty() && this.txtNom.getText().isEmpty()) {
      this.txtId.setText("");
      Limpiar();
      this.lbMostrarImagen.setIcon((Icon)null);
      MostrarTabla4();
      DPagos Prov = new DPagos();
      Prov.setApellidos(this.txtApe.getText());
      (new Metodos_Consulta_Rapida()).consultaFolio4(Prov);
      this.ProximoPago.setDate(Prov.getProximo_Pago());
      this.txtTipo.setText(Prov.getTipo());
      DAltas prov = new DAltas();
      prov.setApellidos(this.txtApe.getText());
      (new PuenteAltas()).PuenteBuscar4(prov);
      this.LbApellido.setText("" + prov.getApellidos());
      String Apellidos = this.txtApe.getText();
      ImageIcon img = (new PuenteAltas()).puenteObtenerImagen4(Apellidos);
      Icon icono = new ImageIcon(img.getImage().getScaledInstance(this.lbMostrarImagen.getWidth(), this.lbMostrarImagen.getHeight(), 1));
      if (img != null) {
        this.lbMostrarImagen.setIcon(icono);
        CalcularDias(this.Hoy, this.ProximoPago);
      } 
      this.TablaDatos.setVisible(true);
    } else if (!this.txtApe.getText().isEmpty() && !this.txtNom.getText().isEmpty()) {
      this.txtId.setText("");
      Limpiar();
      this.lbMostrarImagen.setIcon((Icon)null);
      MostrarTabla2();
      DPagos Prov = new DPagos();
      Prov.setNombre(this.txtNom.getText());
      Prov.setApellidos(this.txtApe.getText());
      (new Metodos_Consulta_Rapida()).consultaFolio2(Prov);
      this.ProximoPago.setDate(Prov.getProximo_Pago());
      this.txtTipo.setText(Prov.getTipo());
      DAltas prov = new DAltas();
      prov.setNombre(this.txtNom.getText());
      prov.setApellidos(this.txtApe.getText());
      (new PuenteAltas()).PuenteBuscar2(prov);
      this.LbNombre.setText("" + prov.getNombre());
      this.LbApellido.setText("" + this.txtApe.getText());
      String Nombre = this.txtNom.getText();
      String Apellidos = this.txtApe.getText();
      ImageIcon img = (new PuenteAltas()).puenteObtenerImagen2(Nombre, Apellidos);
      Icon icono = new ImageIcon(img.getImage().getScaledInstance(this.lbMostrarImagen.getWidth(), this.lbMostrarImagen.getHeight(), 1));
      if (img != null) {
        this.lbMostrarImagen.setIcon(icono);
        CalcularDias(this.Hoy, this.ProximoPago);
      } 
      this.TablaDatos.setVisible(true);
    } }catch(Exception e){System.out.println(e);}
    }//GEN-LAST:event_txtNomActionPerformed

    private void txtApeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApeActionPerformed
try{
        if (this.txtNom.getText().isEmpty() && this.txtApe.getText().isEmpty()) {
      JOptionPane.showMessageDialog(null, "Debes introducir Nombre y Apellido", "Aviso", 1);
    } else if (this.txtApe.getText().isEmpty() && !this.txtNom.getText().isEmpty()) {
      this.txtId.setText("");
      Limpiar();
      this.lbMostrarImagen.setIcon((Icon)null);
      MostrarTabla3();
      DPagos Prov = new DPagos();
      Prov.setNombre(this.txtNom.getText());
      (new Metodos_Consulta_Rapida()).consultaFolio3(Prov);
      this.ProximoPago.setDate(Prov.getProximo_Pago());
      this.txtTipo.setText(Prov.getTipo());
      DAltas prov = new DAltas();
      prov.setNombre(this.txtNom.getText());
      (new PuenteAltas()).PuenteBuscar3(prov);
      this.LbNombre.setText("" + prov.getNombre());
      String Nombre = this.txtNom.getText();
      ImageIcon img = (new PuenteAltas()).puenteObtenerImagen3(Nombre);
      Icon icono = new ImageIcon(img.getImage().getScaledInstance(this.lbMostrarImagen.getWidth(), this.lbMostrarImagen.getHeight(), 1));
      if (img != null) {
        this.lbMostrarImagen.setIcon(icono);
        CalcularDias(this.Hoy, this.ProximoPago);
      } 
      this.TablaDatos.setVisible(true);
    } else if (!this.txtApe.getText().isEmpty() && this.txtNom.getText().isEmpty()) {
      this.txtId.setText("");
      Limpiar();
      this.lbMostrarImagen.setIcon((Icon)null);
      MostrarTabla4();
      DPagos Prov = new DPagos();
      Prov.setApellidos(this.txtApe.getText());
      (new Metodos_Consulta_Rapida()).consultaFolio4(Prov);
      this.ProximoPago.setDate(Prov.getProximo_Pago());
      this.txtTipo.setText(Prov.getTipo());
      DAltas prov = new DAltas();
      prov.setApellidos(this.txtApe.getText());
      (new PuenteAltas()).PuenteBuscar4(prov);
      this.LbApellido.setText("" + prov.getApellidos());
      String Apellidos = this.txtApe.getText();
      ImageIcon img = (new PuenteAltas()).puenteObtenerImagen4(Apellidos);
      Icon icono = new ImageIcon(img.getImage().getScaledInstance(this.lbMostrarImagen.getWidth(), this.lbMostrarImagen.getHeight(), 1));
      if (img != null) {
        this.lbMostrarImagen.setIcon(icono);
        CalcularDias(this.Hoy, this.ProximoPago);
      } 
      this.TablaDatos.setVisible(true);
    } else if (!this.txtApe.getText().isEmpty() && !this.txtNom.getText().isEmpty()) {
      this.txtId.setText("");
      Limpiar();
      this.lbMostrarImagen.setIcon((Icon)null);
      MostrarTabla2();
      DPagos Prov = new DPagos();
      Prov.setNombre(this.txtNom.getText());
      Prov.setApellidos(this.txtApe.getText());
      (new Metodos_Consulta_Rapida()).consultaFolio2(Prov);
      this.ProximoPago.setDate(Prov.getProximo_Pago());
      this.txtTipo.setText(Prov.getTipo());
      DAltas prov = new DAltas();
      prov.setNombre(this.txtNom.getText());
      prov.setApellidos(this.txtApe.getText());
      (new PuenteAltas()).PuenteBuscar2(prov);
      this.LbNombre.setText("" + prov.getNombre());
      this.LbApellido.setText("" + this.txtApe.getText());
      String Nombre = this.txtNom.getText();
      String Apellidos = this.txtApe.getText();
      ImageIcon img = (new PuenteAltas()).puenteObtenerImagen2(Nombre, Apellidos);
      Icon icono = new ImageIcon(img.getImage().getScaledInstance(this.lbMostrarImagen.getWidth(), this.lbMostrarImagen.getHeight(), 1));
      if (img != null) {
        this.lbMostrarImagen.setIcon(icono);
        CalcularDias(this.Hoy, this.ProximoPago);
      } 
      this.TablaDatos.setVisible(true);
    } }catch(Exception e){System.out.println(e);}       // TODO add your handling code here:
    }//GEN-LAST:event_txtApeActionPerformed

    private void txtIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyTyped
char car = evt.getKeyChar();
        if (car < '0' || car > '9')
        evt.consume();           // TODO add your handling code here:
    }//GEN-LAST:event_txtIdKeyTyped

    private void txtApeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApeKeyPressed
    // TODO add your handling code here:
    }//GEN-LAST:event_txtApeKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaRapida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaRapida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaRapida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaRapida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaRapida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Hoy;
    private javax.swing.JLabel LbApellido;
    private javax.swing.JLabel LbNombre;
    private com.toedter.calendar.JDateChooser ProximoPago;
    private javax.swing.JTable TablaDatos;
    private javax.swing.JTextField estado;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbMostrarImagen;
    public javax.swing.JLabel nam;
    private javax.swing.JTextField txtApe;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
